### ISSUE TITLE
마이크로서비스를 위한 싱글사인온 솔루션들을 찾는다. 

### ISSUE THREAD

**Issue by phi4grv** [parti-xyz/parti-sso#1]

**Comment by phi4grv** [comment]
# Casino
- http://blog.codescrum.com/2015/03/31/Single_Sign_On_with_Devise_and_Casino/

**Comment by phi4grv** [comment]
# OAuth
- OmniAuth for client-side and custom implementation for provider
  - http://codetheory.in/rails-devise-omniauth-sso/
- https://github.com/doorkeeper-gem/doorkeeper

**Comment by phi4grv** [comment]
# OpenID Connect
- https://github.com/nov/openid_connect

**Comment by dalikim** [comment]
여기 나온 링크를 모아서 기술 문서로 만들고, 이 이슈는 당분간 잠재울까요?
일단 되자나요. ㅎㅎ
OAuth는 언젠간 꼭 도입하긴 해야하는데요. @parti-xyz/owners

**Comment by phi4grv** [comment]
OAuth를 이용한 싱글사인온을 프로토타입 비슷하게 만들어보고 싶은데
시간이 너무 많이 걸릴듯해서 망설여지네요.

**Comment by dalikim** [comment]
https://github.com/alphagov/signonotron2 요런거 분석해보는건 어때요?

2015년 12월 15일 오후 10:00, royjung notifications@github.com님이 작성:

**Comment by phi4grv** [comment]
https://github.com/nov/openid_connect 부터 시작해 봅니다.
https://github.com/parti-xyz/oidc-provider 에서 진행을 합니다.
일단 이 이슈는 종료합니다.
